//! Effectful stage, review, and promotion transactions.

use std::{fs, io, path::Path};

use liquidfun_test_protocol::{HarnessLimits, ToleranceProfile, decode_scenario_request_jsonl};

use crate::{EmptyWorldAdapter, compare};

use super::{
    domain::{
        ArtifactCandidate, ArtifactKind, CANDIDATE_SCHEMA_VERSION, CandidateMetadata, FixtureError,
        MAX_REPORT_BYTES, PromotionReceipt, ReviewMetadata, ReviewReceipt, ReviewStatus,
        StageRequest, StoredReview,
    },
    replay::{replay_candidate, stage_report, validate_trace_bundle},
    storage::{
        candidate_sha256, destination_path, deterministic_diff, enforce_size,
        ensure_directory_chain, read_confined_file, read_manifest, reject_symlink_chain, sha256,
        sync_directory, update_manifest_atomically, validate_identifier, validate_preset_profile,
        validate_review, validate_revision, write_create_new,
    },
};

/// Validates generated bytes and creates a new confined candidate.
///
/// # Errors
///
/// Returns [`FixtureError`] for untrusted paths, limits, protocol bytes, identity, comparison,
/// signature, or create-new failures. No tracked path is written.
#[allow(
    clippy::too_many_lines,
    reason = "the linear staging transaction keeps every validation before its first write"
)]
pub fn stage_candidate(
    repository_root: &Path,
    request: StageRequest<'_>,
) -> Result<ArtifactCandidate, FixtureError> {
    validate_identifier(request.artifact_id, "artifact")?;
    validate_identifier(request.scenario_id, "scenario")?;
    validate_revision(request.generator_revision)?;
    validate_preset_profile(request.preset, request.session_profile)?;
    let manifest = read_manifest(repository_root)?;
    let limits = HarnessLimits::phase2_default_v1();
    enforce_size(
        "request",
        request.request_bytes,
        limits.input_record_bytes(),
    )?;
    enforce_size("trace", request.trace_bytes, limits.complete_trace_bytes())?;
    enforce_size(
        "stderr",
        request.stderr_bytes,
        limits.retained_stderr_bytes(),
    )?;
    let scenario_request = decode_scenario_request_jsonl(request.request_bytes, &limits)
        .map_err(|error| FixtureError::Replay(error.to_string()))?;
    if scenario_request.scenario().scenario_id().as_str() != request.scenario_id {
        return Err(FixtureError::Replay(
            "scenario identity mismatch".to_owned(),
        ));
    }
    let (trace, identity, identity_bytes) = validate_trace_bundle(
        &scenario_request,
        request.trace_bytes,
        &manifest.oracle_revision,
        &limits,
    )?;
    if identity.cmake_preset() != request.preset {
        return Err(FixtureError::Replay(
            "oracle preset identity mismatch".to_owned(),
        ));
    }
    let mut native = EmptyWorldAdapter::new(&manifest.oracle_revision)
        .map_err(|error| FixtureError::Replay(error.to_string()))?;
    let native_trace = native
        .execute(&scenario_request)
        .map_err(|error| FixtureError::Replay(error.to_string()))?;
    let outcome = compare(&trace, &native_trace, &ToleranceProfile::phase2_v1())
        .map_err(|error| FixtureError::Replay(error.kind().as_str().to_owned()))?;
    let (report_bytes, maybe_signature_json) = stage_report(
        request.artifact_kind,
        outcome,
        request.maybe_failure_signature,
    )?;
    enforce_size("report", &report_bytes, MAX_REPORT_BYTES)?;
    let scenario_bytes = serde_json::to_vec(scenario_request.scenario())?;
    let staging = ensure_directory_chain(repository_root, &["target", "differential", "staging"])?;
    let directory = staging.join(request.artifact_id);
    fs::create_dir(&directory).map_err(|error| {
        if error.kind() == io::ErrorKind::AlreadyExists {
            FixtureError::CandidateExists {
                path: directory.clone(),
            }
        } else {
            FixtureError::Io(error)
        }
    })?;
    let result = (|| {
        let files = [
            ("request.jsonl", request.request_bytes),
            ("trace.jsonl", request.trace_bytes),
            ("report.json", report_bytes.as_slice()),
            ("identity.jsonl", identity_bytes),
            ("stderr.txt", request.stderr_bytes),
            ("scenario.json", scenario_bytes.as_slice()),
        ];
        for (name, bytes) in files {
            write_create_new(&directory.join(name), bytes)?;
        }
        let mut metadata = CandidateMetadata {
            schema_version: CANDIDATE_SCHEMA_VERSION,
            artifact_id: request.artifact_id.to_owned(),
            artifact_kind: request.artifact_kind,
            scenario_id: request.scenario_id.to_owned(),
            scenario_sha256: trace.scenario_sha256().as_str().to_owned(),
            source_json: serde_json::to_string(scenario_request.scenario().source())?,
            protocol_version: scenario_request.protocol_version().get(),
            scenario_schema_version: scenario_request.scenario_schema_version().get(),
            trace_schema_version: scenario_request.requested_trace_schema_version().get(),
            tolerance_profile_version: scenario_request.tolerance_profile_version().get(),
            tolerance_profile_sha256: scenario_request
                .tolerance_profile_sha256()
                .as_str()
                .to_owned(),
            oracle_revision: identity.oracle_revision().to_owned(),
            preset: request.preset.to_owned(),
            session_profile: request.session_profile.to_owned(),
            compiler: format!("{} {}", identity.compiler_id(), identity.compiler_version()),
            target: identity.target().to_owned(),
            flags: vec![
                identity.effective_compile_flags().to_owned(),
                identity.effective_link_flags().to_owned(),
            ],
            generator_revision: request.generator_revision.to_owned(),
            review_status: ReviewStatus::Pending,
            request_sha256: sha256(request.request_bytes),
            trace_sha256: sha256(request.trace_bytes),
            report_sha256: sha256(&report_bytes),
            identity_sha256: sha256(identity_bytes),
            stderr_sha256: sha256(request.stderr_bytes),
            scenario_bytes_sha256: sha256(&scenario_bytes),
            failure_signature_json: maybe_signature_json,
            candidate_sha256: String::new(),
        };
        metadata.candidate_sha256 = candidate_sha256(&metadata);
        write_create_new(
            &directory.join("candidate.toml"),
            toml::to_string_pretty(&metadata)?.as_bytes(),
        )?;
        sync_directory(&directory)?;
        Ok::<(), FixtureError>(())
    })();
    if let Err(error) = result {
        let _ignored = fs::remove_dir_all(&directory);
        return Err(error);
    }
    Ok(ArtifactCandidate {
        artifact_id: request.artifact_id.into(),
        directory: fs::canonicalize(directory)?,
    })
}

/// Replays a staged candidate, renders its deterministic diff, and records explicit review.
///
/// # Errors
///
/// Returns [`FixtureError`] when any candidate byte, identity, signature, path, or metadata field
/// fails revalidation. Accepted evidence remains read-only.
pub fn review_candidate(
    repository_root: &Path,
    artifact_id: &str,
    review: ReviewMetadata<'_>,
) -> Result<ReviewReceipt, FixtureError> {
    validate_review(review)?;
    let replayed = replay_candidate(repository_root, artifact_id)?;
    let destination = destination_path(repository_root, &replayed.metadata)?;
    reject_symlink_chain(repository_root, &destination)?;
    let diff = if destination.exists() {
        deterministic_diff(
            &read_confined_file(&destination, MAX_REPORT_BYTES, "accepted")?,
            &replayed.accepted_bytes,
        )
    } else {
        "accepted artifact is absent\n".to_owned()
    };
    let stored = StoredReview {
        schema_version: CANDIDATE_SCHEMA_VERSION,
        artifact_id: artifact_id.to_owned(),
        candidate_sha256: replayed.metadata.candidate_sha256.clone(),
        reviewer: review.reviewer.to_owned(),
        reviewed_at: review.reviewed_at.to_owned(),
        review_status: review.review_status,
    };
    let review_path = replayed.directory.join("review.toml");
    write_create_new(&review_path, toml::to_string_pretty(&stored)?.as_bytes()).map_err(
        |error| match error {
            FixtureError::Io(inner) if inner.kind() == io::ErrorKind::AlreadyExists => {
                FixtureError::CandidateExists { path: review_path }
            }
            other => other,
        },
    )?;
    sync_directory(&replayed.directory)?;
    Ok(ReviewReceipt {
        artifact_id: artifact_id.into(),
        review_status: review.review_status,
        diff: diff.into_boxed_str(),
    })
}

/// Replays an approved candidate again, promotes with no-clobber semantics, and atomically
/// replaces the artifact manifest.
///
/// # Errors
///
/// Returns [`FixtureError`] unless review is explicit and still bound to unchanged candidate
/// bytes. Existing destinations are never overwritten.
pub fn promote_candidate(
    repository_root: &Path,
    artifact_id: &str,
) -> Result<PromotionReceipt, FixtureError> {
    let replayed = replay_candidate(repository_root, artifact_id)?;
    let review_path = replayed.directory.join("review.toml");
    if !review_path.exists() {
        return Err(FixtureError::ReviewRequired);
    }
    let review: StoredReview = toml::from_str(
        &String::from_utf8(read_confined_file(
            &review_path,
            MAX_REPORT_BYTES,
            "review",
        )?)
        .map_err(|error| FixtureError::Replay(error.to_string()))?,
    )?;
    if review.schema_version != CANDIDATE_SCHEMA_VERSION
        || review.artifact_id != artifact_id
        || review.candidate_sha256 != replayed.metadata.candidate_sha256
        || review.review_status != ReviewStatus::Approved
    {
        return Err(FixtureError::ReviewRequired);
    }
    let (parent, filename) = match replayed.metadata.artifact_kind {
        ArtifactKind::ReviewedTrace => (
            ensure_directory_chain(repository_root, &["reference", "artifacts", "traces"])?,
            format!("{}.jsonl", replayed.metadata.scenario_id),
        ),
        ArtifactKind::MinimizedRegression => (
            ensure_directory_chain(repository_root, &["scenarios", "regressions"])?,
            format!("{}.json", replayed.metadata.scenario_id),
        ),
    };
    let destination = parent.join(filename);
    if destination.exists() {
        return Err(FixtureError::DestinationExists { path: destination });
    }
    let temporary = parent.join(format!(".promoting-{artifact_id}.tmp"));
    write_create_new(&temporary, &replayed.accepted_bytes)?;
    if let Err(error) = fs::hard_link(&temporary, &destination) {
        let _ignored = fs::remove_file(&temporary);
        if error.kind() == io::ErrorKind::AlreadyExists {
            return Err(FixtureError::DestinationExists { path: destination });
        }
        return Err(FixtureError::Io(error));
    }
    let artifact_hash = sha256(&replayed.accepted_bytes);
    let manifest_result = update_manifest_atomically(
        repository_root,
        &replayed.metadata,
        &destination,
        &artifact_hash,
        artifact_id,
    );
    if let Err(error) = manifest_result {
        let _ignored = fs::remove_file(&destination);
        let _ignored = fs::remove_file(&temporary);
        return Err(error);
    }
    fs::remove_file(&temporary)?;
    sync_directory(&parent)?;
    Ok(PromotionReceipt {
        artifact_id: artifact_id.into(),
        artifact_path: destination,
        manifest_path: repository_root.join("reference/artifacts/manifest.toml"),
        sha256: artifact_hash.into_boxed_str(),
    })
}
