use std::collections::BTreeMap;
use std::fmt::{Arguments, Write as _};

use super::{
    ApplicabilityStatus, CompatibilityKind, CompatibilityLedger, EvidenceRecord, EvidenceStatus,
    ReleaseReadiness,
};

const LEGEND: [(&str, &str); 8] = [
    (
        "investigated",
        "Upstream behavior and scope have cited research evidence.",
    ),
    (
        "planned",
        "A repository plan or roadmap explicitly owns the work.",
    ),
    (
        "implemented",
        "Native Rust behavior exists; compilation alone is not evidence.",
    ),
    ("unit_tested", "Focused native Rust behavior tests exist."),
    (
        "differentially_validated",
        "Semantic behavior has passed the pinned C++ comparison policy.",
    ),
    (
        "platform_validated",
        "Behavior has passed on named supported platform evidence.",
    ),
    (
        "documented_difference",
        "A reviewed intentional behavioral or API difference is documented.",
    ),
    (
        "intentionally_unsupported",
        "A reviewed exclusion is explicit and carries supporting evidence.",
    ),
];

pub(super) fn render(ledger: &CompatibilityLedger, readiness: &ReleaseReadiness) -> String {
    let mut output = String::new();
    render_header(&mut output, ledger);
    render_release_readiness(&mut output, ledger, readiness);
    render_counts(&mut output, ledger);
    render_kind_tables(&mut output, ledger);
    render_release_outcomes(&mut output, ledger);
    output
}

fn render_header(output: &mut String, ledger: &CompatibilityLedger) {
    output.push_str("<!-- @generated by `cargo xtask inventory generate`; DO NOT EDIT. -->\n\n");
    output.push_str("# LiquidFun Compatibility Inventory\n\n");
    output.push_str("The machine-readable source of truth is `reference/compatibility.json`. ");
    output.push_str(
        "This report does not claim implementation or parity where evidence is absent.\n\n",
    );
    output.push_str("## Oracle identity\n\n");
    append(
        output,
        format_args!("- Revision: `{}`\n", ledger.oracle_revision),
    );
    append(
        output,
        format_args!("- Schema: {}\n", ledger.schema_version),
    );
    append(
        output,
        format_args!("- Compatibility rows: {}\n\n", ledger.entries.len()),
    );
    output.push_str("## Evidence-state legend\n\n");
    output.push_str("Each dimension is independent. `Evidenced` requires at least one cited reference; `Not evidenced` is an explicit gap.\n\n");
    output.push_str("| Dimension | Definition |\n| --- | --- |\n");
    for (dimension, definition) in LEGEND {
        append(output, format_args!("| `{dimension}` | {definition} |\n"));
    }
}

fn render_release_readiness(
    output: &mut String,
    ledger: &CompatibilityLedger,
    readiness: &ReleaseReadiness,
) {
    output.push_str("\n## Release readiness closure\n\n");
    output.push_str("Status: **zero unexplained compatibility gaps**. This closure is derived from exact identity joins; local command success never promotes evidence.\n\n");
    output.push_str("| Closure measure | Count |\n| --- | ---: |\n");
    for (label, count) in [
        ("Compatibility identities", ledger.entries.len()),
        (
            "Release disposition joins",
            ledger.release_dispositions.len(),
        ),
        ("D1 canonical rows", readiness.d1_rows),
        ("D2 supported rows (orthogonal)", readiness.d2_rows),
        ("Terminal corpus rows", readiness.corpus_terminal_rows),
        (
            "Reviewed difference rows",
            readiness.reviewed_difference_rows,
        ),
        (
            "Intentional unsupported rows",
            readiness.intentional_unsupported_rows,
        ),
        ("Terminal corpus items", readiness.corpus_items),
        ("Unexplained rows", 0),
        ("Nonterminal corpus items", 0),
        ("Stale or mixed-commit evidence", 0),
    ] {
        append(output, format_args!("| {label} | {count} |\n"));
    }
    output.push_str("\n### Machine authorities\n\n");
    output.push_str(
        "- D1 parity: compatibility evidence joined to pinned tolerance profiles and exact reviewed evidence references.\n",
    );
    output.push_str(
        "- D2 support: `reference/platform/support.json`; D2 never promotes D1 parity.\n",
    );
    output.push_str(
        "- Corpus closure: `reference/upstream-corpus.json`; every item must have one terminal review outcome.\n",
    );
    output.push_str(
        "- Artifact, regression, performance, and coverage contracts are schema-checked. Coverage and performance are explicitly non-parity authorities.\n",
    );
}

fn render_counts(output: &mut String, ledger: &CompatibilityLedger) {
    output.push_str("\n## Inventory counts\n\n");
    output.push_str(
        "| Kind | Rows | Applicable | Reviewed exclusions |\n| --- | ---: | ---: | ---: |\n",
    );
    for kind in CompatibilityKind::ALL {
        let rows: Vec<_> = ledger
            .entries
            .iter()
            .filter(|entry| entry.kind == kind)
            .collect();
        let applicable = rows
            .iter()
            .filter(|entry| entry.applicability.status == ApplicabilityStatus::Applicable)
            .count();
        append(
            output,
            format_args!(
                "| `{}` | {} | {} | {} |\n",
                kind.as_str(),
                rows.len(),
                applicable,
                rows.len() - applicable
            ),
        );
    }
    output.push_str("\n## Evidence counts\n\n");
    output.push_str("| Dimension | Evidenced | Not evidenced |\n| --- | ---: | ---: |\n");
    let mut evidence_counts: BTreeMap<&str, usize> = BTreeMap::new();
    for entry in &ledger.entries {
        for (dimension, record) in entry.evidence.records() {
            if record.status == EvidenceStatus::Evidenced {
                *evidence_counts.entry(dimension).or_default() += 1;
            }
        }
    }
    for (dimension, _) in LEGEND {
        let evidenced = evidence_counts.get(dimension).copied().unwrap_or_default();
        append(
            output,
            format_args!(
                "| `{dimension}` | {evidenced} | {} |\n",
                ledger.entries.len() - evidenced
            ),
        );
    }
}

fn render_kind_tables(output: &mut String, ledger: &CompatibilityLedger) {
    for kind in CompatibilityKind::ALL {
        append(output, format_args!("\n## {}\n\n", title(kind.as_str())));
        output.push_str("| ID | Upstream | Rust target | Applicability | I | P | Impl | Unit | Diff | Platform | Delta | Unsupported |\n");
        output.push_str(
            "| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n",
        );
        for entry in ledger.entries.iter().filter(|entry| entry.kind == kind) {
            let symbol = entry
                .upstream_symbol
                .as_deref()
                .map(|value| format!(" (`{}`)", markdown(value)))
                .unwrap_or_default();
            append(
                output,
                format_args!(
                    "| `{}` | `{}`{} | `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                    markdown(&entry.id),
                    markdown(&entry.upstream_path),
                    symbol,
                    markdown(&entry.rust_target),
                    applicability(entry.applicability.status),
                    marker(&entry.evidence.investigated),
                    marker(&entry.evidence.planned),
                    marker(&entry.evidence.implemented),
                    marker(&entry.evidence.unit_tested),
                    marker(&entry.evidence.differentially_validated),
                    marker(&entry.evidence.platform_validated),
                    marker(&entry.evidence.documented_difference),
                    marker(&entry.evidence.intentionally_unsupported),
                ),
            );
        }
    }
}

fn render_release_outcomes(output: &mut String, ledger: &CompatibilityLedger) {
    output.push_str("\n## Release dispositions\n\n");
    output.push_str("Each compatibility identity has exactly one reviewed release outcome. These outcomes do not erase independent evidence gaps shown above.\n\n");
    output.push_str("| ID | Outcome | Rationale | Authorities |\n| --- | --- | --- | --- |\n");
    for disposition in &ledger.release_dispositions {
        append(
            output,
            format_args!(
                "| `{}` | {} | {} | {} |\n",
                markdown(&disposition.id),
                disposition.outcome.as_str(),
                markdown(&disposition.rationale),
                disposition
                    .references
                    .iter()
                    .map(|reference| format!("`{}`", markdown(reference)))
                    .collect::<Vec<_>>()
                    .join("<br>"),
            ),
        );
    }
}

fn append(output: &mut String, arguments: Arguments<'_>) {
    output
        .write_fmt(arguments)
        .expect("writing formatted compatibility data to a String cannot fail");
}

fn marker(record: &EvidenceRecord) -> &'static str {
    match record.status {
        EvidenceStatus::Evidenced => "yes",
        EvidenceStatus::NotEvidenced => "no",
    }
}

const fn applicability(status: ApplicabilityStatus) -> &'static str {
    match status {
        ApplicabilityStatus::Applicable => "applicable",
        ApplicabilityStatus::ReviewedExclusion => "reviewed exclusion",
    }
}

fn title(value: &str) -> String {
    let mut characters = value.chars();
    let Some(first) = characters.next() else {
        return String::new();
    };
    format!("{}{}", first.to_uppercase(), characters.as_str()).replace('_', " ")
}

fn markdown(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
