pub(super) mod validation;
pub(super) const USAGE: &str = "Usage: cargo xtask docs check";
const TABLE_HEADING: &str = "## Testing layer contract";
const COLUMNS: [&str; 9] = [
    "Layer",
    "Status",
    "Purpose",
    "Command",
    "Prerequisites",
    "Reports and failure artifacts",
    "Retry policy",
    "Placement",
    "Semantic interpretation",
];
const ALLOWED_STATUSES: [&str; 2] = ["current", "deferred"];
const ALLOWED_PLACEMENTS: [&str; 4] = ["local", "pull request", "scheduled", "manual release"];
const PLACEHOLDERS: [&str; 5] = ["TODO", "TBD", "PLACEHOLDER", "REPLACE_ME", "REPLACE WITH"];
pub(super) const DOCUMENT_CONTRACTS: [(&str, &[&str]); 3] = [
    (
        "ARCHITECTURE.md",
        &[
            "## Phase 4 math and numerical boundaries",
            "`Vec2`, `Vec3`, `Vec4`, `Mat22`, `Mat33`, `Rotation`, `Transform`, and `Sweep`",
            "(MKS), angles use radians",
            "operations are column-major",
            "external C++ adapter",
            "None is a dependency or feature of `liquidfun`",
        ],
    ),
    (
        "TESTING.md",
        &[
            "## Phase 4 numerical policy",
            "The four float policies are",
            "`ExactBits`",
            "`Ulps`",
            "`Absolute`",
            "`AbsoluteRelative`",
            "Arithmetic NaN is a mismatch",
            "Positive and negative zero are distinct by default",
            "`Operation`",
            "`PhaseLocal`",
            "`ScenarioSteps(n)`",
            "D1 is canonical parity",
            "promote canonical fixtures.",
            "D2 cannot promote canonical fixtures",
            "## Phase 4 math-probe commands",
            "cargo xtask differential compare --scenario math-probes --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential compare --scenario math-probes --preset oracle-release --session-profile one-shot",
            "cargo xtask differential replay --scenario math-probes --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential verify-determinism --scenario math-probes --preset oracle-debug --runs 2",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "| `implemented` | 64 | 117 |",
            "| `unit_tested` | 64 | 117 |",
            "| `differentially_validated` | 63 | 118 |",
            "| `platform_validated` | 46 | 135 |",
            "| `documented_difference` | 51 | 130 |",
            "`subsystem.common-math-and-settings`",
            "`public-api.liquidfun-box2d-box2d-common-b2math-h`",
            "`public-api.liquidfun-box2d-box2d-common-b2settings-h`",
            "| applicable | yes | yes | yes | yes | no | no | yes | no |",
        ],
    ),
];
pub(super) const PHASE5_DOCUMENT_CONTRACTS: [(&str, &[&str]); 3] = [
    (
        "ARCHITECTURE.md",
        &[
            "## Phase 5 collision boundaries",
            "`CircleShape`, `EdgeShape`, `PolygonShape`, and `ChainShape`",
            "`[0.5, 2.0]`",
            "`distance < 10.0 * EPSILON`",
            "Collect-all query and ray membership is set-like",
            "The `differential-internals` feature is non-default, `#[doc(hidden)]`",
            "the Phase 5 portion of `COLL-05`",
            "contact persistence or",
            "Phase 6",
            "Bright Builds architecture",
        ],
    ),
    (
        "TESTING.md",
        &[
            "## Phase 5 collision comparison policy",
            "Exact `u32` bit transport",
            "`ExactBits` policies",
            "`Operation`",
            "`PhaseLocal`",
            "D0 requires two byte-identical",
            "D1 requires the canonical pinned Rust 1.97.0 and Clang 22.1.8",
            "D2-scoped",
            "78-case `collision-probes`",
            "world contact lifecycle remains",
            "## Phase 5 collision-probe commands",
            "cargo xtask differential compare --scenario collision-probes --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential compare --scenario collision-probes --preset oracle-release --session-profile one-shot",
            "cargo xtask differential replay --scenario collision-probes --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential verify-determinism --scenario collision-probes --preset oracle-debug --runs 2",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "| `subsystem.collision-broad-phase` | `liquidfun/Box2D/Box2D/Collision` | `liquidfun::collision` | applicable | yes | yes | yes | yes | yes | no | yes | no |",
            "| `subsystem.collision-distance-and-toi` | `liquidfun/Box2D/Box2D/Collision` | `liquidfun::collision` | applicable | yes | yes | yes | yes | yes | no | yes | no |",
            "| `subsystem.collision-shapes-and-manifolds` | `liquidfun/Box2D/Box2D/Collision/Shapes` | `liquidfun::collision` | applicable | yes | yes | yes | yes | yes | no | yes | no |",
        ],
    ),
];
pub(super) const PHASE6_DOCUMENT_CONTRACTS: [(&str, &[&str]); 4] = [
    (
        "ARCHITECTURE.md",
        &[
            "## Phase 6 rigid-world boundaries",
            "`BodyDef` and `FixtureDef`",
            "`World::set_body_transform`",
            "`World::reset_body_mass_data`",
            "`World::set_body_mass_data`",
            "`World::set_fixture_sensor`",
            "`World::set_fixture_filter`",
            "creation-time mixed friction and restitution",
            "`FindPairs`, `UpdateContacts`, `Hook`, `Solve`, `Unlock`",
            "one static/dynamic contact",
            "Aggregate mass is a validate-before-commit transaction",
            "`BodyTypeChangeError` and `FixtureDestructionError`",
            "positive-origin inertia must remain finite and strictly positive",
            "current checkout and selected preset",
            "adapter-source and effective compile-command digests",
            "Admission requires at least one dynamic body",
            "timestep bits `0x3c888889`, eight",
            "at most 128 actions",
            "origin inertia exactly zero follows the pinned no-inertia branch",
            "authority are checked before every candidate",
            "`oracle-asan-ubsan` lane executes the C++ protocol target",
            "No durable contact identity",
            "Phase 7",
            "Phase 8",
        ],
    ),
    (
        "TESTING.md",
        &[
            "## Phase 6 rigid-world comparison policy",
            "`phase6-v1`",
            "`non_colliding_body_fixture_lifecycle`",
            "`single_contact_lifecycle`",
            "declaration-first",
            "Local successful comparisons are D2",
            "D0 requires exactly two byte-identical",
            "D1 remains the only fixture-promotion authority",
            "## Phase 6 rigid-world commands",
            "cargo xtask differential compare --scenario rigid-world --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential compare --scenario rigid-world --preset oracle-release --session-profile one-shot",
            "cargo xtask differential replay --scenario rigid-world --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential verify-determinism --scenario rigid-world --preset oracle-debug --runs 2",
            "cmake --build target/reference/oracle-asan-ubsan --target liquidfun-reference-protocol-tests",
            "ctest --test-dir target/reference/oracle-asan-ubsan --output-on-failure --no-tests=error -R '^liquidfun-reference-protocol$'",
            "cargo xtask differential compare --scenario rigid-world --preset oracle-asan-ubsan --session-profile one-shot",
            "retains failures for seven days",
            "`aggregate-mass-atomicity`",
            "`non-dynamic-contact-admission`",
            "`ignored-step-parameters`",
            "`rigid-action-bound-mismatch`",
            "`invalid-centered-inertia-boundary`",
            "`rigid-staging-not-integrated`",
            "`rigid-sanitizer-not-executed`",
            "`implicit-aggregate-mass-atomicity`",
            "`zero-centered-inertia-boundary`",
            "`rigid-fixture-checkout-provenance`",
            "local debug/release and replay passes are D2",
            "same-build byte-identical runs are D0",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "| `subsystem.contacts-and-filtering` | `liquidfun/Box2D/Box2D/Dynamics/Contacts` | `liquidfun::dynamics::contacts` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `subsystem.rigid-bodies-and-fixtures` | `liquidfun/Box2D/Box2D/Dynamics` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2body-h` | `liquidfun/Box2D/Box2D/Dynamics/b2Body.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2fixture-h` | `liquidfun/Box2D/Box2D/Dynamics/b2Fixture.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2contactmanager-h` | `liquidfun/Box2D/Box2D/Dynamics/b2ContactManager.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2world-h` | `liquidfun/Box2D/Box2D/Dynamics/b2World.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-contacts-b2circlecontact-h` | `liquidfun/Box2D/Box2D/Dynamics/Contacts/b2CircleContact.h` | `liquidfun::dynamics::contacts` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-contacts-b2contactsolver-h` | `liquidfun/Box2D/Box2D/Dynamics/Contacts/b2ContactSolver.h` | `liquidfun::dynamics::contacts` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-contacts-b2polygoncontact-h` | `liquidfun/Box2D/Box2D/Dynamics/Contacts/b2PolygonContact.h` | `liquidfun::dynamics::contacts` | applicable | yes | yes | no | no | no | no | no | no |",
            "| `source-area.liquidfun-box2d-box2d-dynamics` | `liquidfun/Box2D/Box2D/Dynamics` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `source-area.liquidfun-box2d-box2d-dynamics-contacts` | `liquidfun/Box2D/Box2D/Dynamics/Contacts` | `liquidfun::dynamics::contacts` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
        ],
    ),
    (
        "protocol/fixtures/accepted/rigid-world-request.jsonl",
        &[
            "static_kinematic_overlap_rejected",
            "kinematic_kinematic_overlap_rejected",
        ],
    ),
];
pub(super) const PHASE7_DOCUMENT_CONTRACTS: [(&str, &[&str]); 4] = [
    (
        "crates/liquidfun/src/lib.rs",
        &[
            "# Phase 7 checked rigid-world contract",
            "`WakePolicy::PreserveSleep`",
            "`StepConfiguration`",
            "`StepCompletion::ContinuousPending`",
            "`ContinuousProgress`",
            "`World::query_aabb`",
            "`World::ray_cast`",
            "`World::shift_origin`",
            "private and resumable",
            "successful step",
        ],
    ),
    (
        "ARCHITECTURE.md",
        &[
            "## Phase 7 rigid solver, world operations, and CCD boundaries",
            "body and contact source order",
            "CCD candidate, cache, and TOI counter state remains private",
            "`ContinuousProgress`",
            "query occurrences are multiplicity-preserving multisets",
            "hits within the registered fraction-policy boundary band, are",
            "callback visitation order is intentionally unspecified",
            "out-of-process",
            "Cargo-only",
            "local D2",
        ],
    ),
    (
        "TESTING.md",
        &[
            "## Phase 7 rigid-world comparison policy",
            "`phase7-v1`",
            "nine-family",
            "query occurrences as a multiplicity-preserving multiset",
            "fraction-policy boundary band, as a multiplicity-preserving multiset",
            "local debug, replay, and sanitizer passes are D2",
            "exactly two byte-identical same-build runs are D0",
            "D3 review remains pending",
            "cargo xtask differential replay --scenario rigid-world --preset oracle-debug --session-profile one-shot",
            "cargo xtask differential compare --scenario rigid-world --preset oracle-asan-ubsan --session-profile one-shot",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "| `implemented` | 64 | 117 |",
            "| `unit_tested` | 64 | 117 |",
            "| `differentially_validated` | 63 | 118 |",
            "| `platform_validated` | 46 | 135 |",
            "| `documented_difference` | 51 | 130 |",
            "| `subsystem.rigid-islands-and-solver` | `liquidfun/Box2D/Box2D/Dynamics` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `subsystem.world-operations-and-observation` | `liquidfun/Box2D/Box2D/Dynamics` | `liquidfun::world` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2island-h` | `liquidfun/Box2D/Box2D/Dynamics/b2Island.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-b2timestep-h` | `liquidfun/Box2D/Box2D/Dynamics/b2TimeStep.h` | `liquidfun::dynamics` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
        ],
    ),
];
const PHASE8_SIGNOFF: &str =
    "canonical scalar rigid-body and joint differential sign-off for the closed Phase 8 corpus";
const PHASE8_PLATFORM_VALIDATED_ROWS: usize = 33;
const PHASE8_RUN: &str = "29383445374";
const PHASE8_HEAD: &str = "beb98bd74b1d26ab0a96c6be33ce1926d349abf0";
const PHASE8_RUN_URL: &str =
    "https://github.com/bright-builds-llc/liquidfun-rs/actions/runs/29383445374";
const PHASE8_CANONICAL_IDENTITY: &str =
    "phase8-canonical-29383445374-beb98bd74b1d26ab0a96c6be33ce1926d349abf0/identity.json";
const PHASE8_SANITIZER_IDENTITY: &str =
    "phase8-sanitizer-29383445374-beb98bd74b1d26ab0a96c6be33ce1926d349abf0/identity.json";
pub(super) const PHASE8_DOCUMENT_CONTRACTS: [(&str, &[&str]); 4] = [
    (
        "crates/liquidfun/src/lib.rs",
        &[
            "# Phase 8 joints, rope, and callback contract",
            PHASE8_SIGNOFF,
            "all eleven joint kinds",
            "standalone [`rope::Rope`]",
        ],
    ),
    (
        "ARCHITECTURE.md",
        &[
            "## Phase 8 joints, rope, callbacks, and rigid sign-off boundaries",
            PHASE8_SIGNOFF,
            "19 required witness families",
            PHASE8_RUN,
            PHASE8_HEAD,
            "phase8-canonical-29383445374-beb98bd74b1d26ab0a96c6be33ce1926d349abf0",
            "phase8-sanitizer-29383445374-beb98bd74b1d26ab0a96c6be33ce1926d349abf0",
            "Rust 1.97.0, CMake 4.3.3, Ninja 1.13.2, and Clang 22.1.8",
            "7f20402173fd143a3988c921bc384459c6a858f2",
            "`phase8-v1`",
        ],
    ),
    (
        "TESTING.md",
        &[
            "## Phase 8 canonical rigid-world sign-off",
            PHASE8_SIGNOFF,
            "19 required witness families",
            PHASE8_RUN,
            PHASE8_HEAD,
            "canonical-linux",
            "sanitizer-linux",
            "RIGD-10",
            "D3",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "| `implemented` | 64 | 117 |",
            "| `unit_tested` | 64 | 117 |",
            "| `differentially_validated` | 63 | 118 |",
            "| `platform_validated` | 46 | 135 |",
            "| `documented_difference` | 51 | 130 |",
            "| `subsystem.joints` | `liquidfun/Box2D/Box2D/Dynamics/Joints` | `liquidfun::dynamics::joints` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `subsystem.rope` | `liquidfun/Box2D/Box2D/Rope` | `liquidfun::rope` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-dynamics-joints-b2joint-h` | `liquidfun/Box2D/Box2D/Dynamics/Joints/b2Joint.h` | `liquidfun::dynamics::joints` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
            "| `public-api.liquidfun-box2d-box2d-rope-b2rope-h` | `liquidfun/Box2D/Box2D/Rope/b2Rope.h` | `liquidfun::rope` | applicable | yes | yes | yes | yes | yes | yes | yes | no |",
        ],
    ),
];
pub(super) const PHASE12_PUBLIC_DOCUMENT_CONTRACTS: [(&str, &[&str]); 5] = [
    (
        "README.md",
        &[
            "## Maturity and evidence",
            "version `0.0.0`",
            "this repository has not declared",
            "a parity-bearing v1 release candidate",
            "[compatibility inventory](COMPATIBILITY.md)",
            "`cargo xtask release audit`",
            "not release-ready",
            "`release-candidate` workflow run",
            "`cargo xtask release attestation validate`",
            "## Cargo-only install and use",
            "Rust 1.92.0",
            "Rust 1.97.0",
            "cargo build -p liquidfun",
            "## Platform support",
            "`x86_64-unknown-linux-gnu`",
            "`aarch64-unknown-linux-gnu`",
            "`aarch64-apple-darwin`",
            "`x86_64-pc-windows-msvc`",
            "`x86_64-apple-darwin`",
            "`conditional_supported`",
            "90 days",
            "D2 portability evidence",
            "## Headless, catalog, and testbed workflows",
            "cargo xtask catalog list",
            "cargo xtask catalog run --scenario rigid-stack-stability",
            "cargo run -p liquidfun-testbed -- --capability-check",
            "cargo run -p liquidfun-testbed --bin interactive",
            "## Optional C++ oracle",
            "git submodule update --init --recursive third_party/liquidfun",
            "CMake 3.25 or newer",
            "## Contributing and licensing",
            "[CONTRIBUTING.md](CONTRIBUTING.md)",
            "MIT-licensed",
            "[THIRD_PARTY_NOTICES.md](THIRD_PARTY_NOTICES.md)",
        ],
    ),
    (
        "CONTRIBUTING.md",
        &[
            "### Bootstrap",
            "Rust 1.92.0",
            "Rust 1.97.0",
            "### Markdown",
            "mdformat 1.0.0 under Python 3.13",
            "just markdown-check",
            "### Ordered local gates",
            "cargo fmt --all",
            "cargo clippy --all-targets --all-features -- -D warnings",
            "cargo build --all-targets --all-features",
            "cargo test --all-features",
            "### CI placement",
            "### Evidence and generated files",
            "### Regression promotion",
            "### Compatibility sign-off",
            "`cargo xtask release audit`",
        ],
    ),
    (
        "COMPATIBILITY.md",
        &[
            "Status: **not release-ready**",
            "no completed full-SHA `release-candidate` workflow run",
            "run-bound release attestation",
        ],
    ),
    (
        "RELEASE.md",
        &[
            "# Release process",
            "## Current release status",
            "not release-ready",
            "`release-candidate` workflow run",
            "`cargo xtask release attestation validate`",
            "## Versioning and MSRV",
            "Semantic Versioning",
            "v1.0.x",
            "Rust 1.92.0",
            "Rust 1.97.0",
            "## Freeze the source candidate",
            "full 40-hex source-candidate SHA",
            "## Audit the frozen candidate",
            "zero unexplained applicable gaps",
            "cargo xtask release audit",
            "## Reuse the exact package",
            "SHA-256",
            "rust-version = \"1.92\"",
            "## Review notices and evidence",
            "## Attest after the source freeze",
            "cargo xtask release attestation validate-worktree",
            "--attestation-commit <full-attestation-commit-sha>",
            "## Publication dry run",
            "cargo publish -p liquidfun --dry-run",
            "## Publish or do not publish",
            "Publication has no technical rollback",
        ],
    ),
    (
        "SAFETY.md",
        &[
            "## Identity and invalidation",
            "## Contacts and callbacks",
            "## Owned particle buffers",
            "## Renderer and oracle isolation",
            "## Panic policy",
            "unsafe_code = \"forbid\"",
        ],
    ),
];
const FORBIDDEN_PHASE5_CLAIMS: [&str; 9] = [
    "full parity",
    "production ready",
    "all platforms validated",
    "query order is guaranteed",
    "global epsilon",
    "cargo xtask differential d0",
    "packed contact keys are public",
    "dynamictree exposes public iteration",
    "phase 6 is complete",
];
const FORBIDDEN_PHASE6_CLAIMS: [&str; 15] = [
    "full rigid parity",
    "public durable contacts",
    "mutable shapes",
    "global epsilon",
    "general solver is implemented",
    "complete island solver",
    "forces are implemented",
    "sleeping is implemented",
    "ccd is implemented",
    "world queries are implemented",
    "world configuration is implemented",
    "joint solving is implemented",
    "platform validated",
    "raw contact identity",
    "raw proxy identity",
];
const FORBIDDEN_PHASE7_CLAIMS: [&str; 10] = [
    "complete rigid solver",
    "complete rigid-world parity",
    "d3-validated",
    "d3 validated",
    "phase 7 platform validated",
    "multi-platform parity",
    "query callbacks are ordered",
    "ray callbacks are ordered",
    "public ccd cache",
    "public toi counter",
];
const FORBIDDEN_PHASE8_CLAIMS: [&str; 6] = [
    "rigd-10 is complete",
    "particle parity is complete",
    "cross-platform parity is complete",
    "performance is validated",
    "the testbed is complete",
    "release ready",
];
const FORBIDDEN_CURRENT_CLAIMS: [&str; 6] = [
    "early vertical-slice stage",
    "do not use this crate for simulation yet",
    "particles remain pending",
    "the testbed remains pending",
    "release audit has passed",
    "faster than c++",
];

#[derive(Clone, Copy)]
pub(super) struct LayerRule {
    name: &'static str,
    command: &'static str,
    prerequisite: &'static str,
    artifact: &'static str,
    retry: &'static str,
    semantics: &'static str,
}

#[derive(serde::Deserialize)]
struct CompatibilityEvidenceLedger {
    entries: Vec<CompatibilityEvidenceEntry>,
}

#[derive(serde::Deserialize)]
struct CompatibilityEvidenceEntry {
    evidence: CompatibilityEvidence,
}

#[derive(serde::Deserialize)]
struct CompatibilityEvidence {
    platform_validated: PlatformEvidence,
}

#[derive(serde::Deserialize)]
struct PlatformEvidence {
    status: String,
    references: Vec<String>,
}

pub(super) const LAYER_RULES: [LayerRule; 12] = [
    LayerRule {
        name: "unit",
        command: "cargo test --workspace --lib",
        prerequisite: "Rust 1.97.0",
        artifact: "test output",
        retry: "No deterministic retry",
        semantics: "focused behavior",
    },
    LayerRule {
        name: "integration/API",
        command: "cargo test --workspace --tests",
        prerequisite: "Rust 1.97.0",
        artifact: "test output",
        retry: "No deterministic retry",
        semantics: "supported API",
    },
    LayerRule {
        name: "doctest",
        command: "cargo test --workspace --doc",
        prerequisite: "Rust 1.97.0",
        artifact: "rustdoc output",
        retry: "No deterministic retry",
        semantics: "documentation example",
    },
    LayerRule {
        name: "upstream compatibility",
        command: "cargo xtask upstream verify",
        prerequisite: "initialized submodule",
        artifact: "target/reference",
        retry: "No deterministic retry",
        semantics: "oracle infrastructure",
    },
    LayerRule {
        name: "differential",
        command: "cargo xtask differential compare",
        prerequisite: "oracle-debug",
        artifact: "target/differential/failures",
        retry: "No deterministic retry",
        semantics: "physics mismatch",
    },
    LayerRule {
        name: "property",
        command: "cargo test --workspace property",
        prerequisite: "Rust 1.97.0",
        artifact: "minimized input",
        retry: "No deterministic retry",
        semantics: "invariant",
    },
    LayerRule {
        name: "checked-in regression",
        command: "cargo xtask differential replay",
        prerequisite: "reviewed trace",
        artifact: "scenarios/regressions",
        retry: "No deterministic retry",
        semantics: "same failure signature",
    },
    LayerRule {
        name: "fuzz",
        command: "cargo fuzz run",
        prerequisite: "pinned nightly",
        artifact: "fuzz/artifacts",
        retry: "No deterministic retry",
        semantics: "harness failure",
    },
    LayerRule {
        name: "Miri/UB-aliasing",
        command: "cargo miri test",
        prerequisite: "pinned nightly",
        artifact: "Miri diagnostics",
        retry: "No deterministic retry",
        semantics: "harness failure",
    },
    LayerRule {
        name: "native sanitizer",
        command: "UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1",
        prerequisite: "Clang 22.1.8",
        artifact: "target/differential/failures",
        retry: "No deterministic retry",
        semantics: "harness failure",
    },
    LayerRule {
        name: "benchmark",
        command: "cargo bench --workspace",
        prerequisite: "controlled hardware",
        artifact: "target/criterion",
        retry: "No deterministic retry",
        semantics: "performance evidence, not parity",
    },
    LayerRule {
        name: "coverage",
        command: "cargo llvm-cov",
        prerequisite: "llvm-tools-preview",
        artifact: "target/llvm-cov",
        retry: "No deterministic retry",
        semantics: "coverage is not parity",
    },
];
