//! Deterministic human projection of the validated semantic corpus authority.

use std::collections::BTreeMap;
use std::fmt::{Arguments, Write as _};

use super::corpus::model::{
    Applicability, CompatibilityImpact, CorpusManifest, TerminalDisposition,
};

pub(super) fn render(manifest: &CorpusManifest) -> String {
    let mut output = String::new();
    output.push_str(
        "<!-- @generated by `cargo xtask inventory corpus generate-report`; DO NOT EDIT. -->\n\n",
    );
    output.push_str("# Upstream Semantic Corpus\n\n");
    output.push_str(
        "The machine-readable authority is `reference/upstream-corpus.json`. This projection records reviewed accounting and does not widen compatibility claims.\n\n",
    );
    render_identity(&mut output, manifest);
    render_counts(&mut output, manifest);
    render_outcomes(&mut output, manifest);
    output
}

fn render_identity(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("## Authority identity\n\n");
    append(
        output,
        format_args!("- Oracle revision: `{}`\n", manifest.oracle_revision()),
    );
    append(
        output,
        format_args!("- Semantic items: {}\n", manifest.items().len()),
    );
    append(
        output,
        format_args!("- Unresolved items: {}\n", unresolved_count(manifest)),
    );
}

fn render_counts(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("\n## Kind totals\n\n");
    output.push_str("| Kind | Items |\n| --- | ---: |\n");
    let mut kind_counts = BTreeMap::new();
    let mut disposition_counts = BTreeMap::new();
    let mut impact_counts = BTreeMap::new();
    let mut applicability_counts = BTreeMap::new();
    for item in manifest.items() {
        *kind_counts.entry(item.kind().as_str()).or_insert(0_usize) += 1;
        if let Some(disposition) = item.disposition() {
            *disposition_counts
                .entry(disposition.as_str())
                .or_insert(0_usize) += 1;
        }
        if let Some(impact) = item.compatibility_impact() {
            *impact_counts.entry(impact.as_str()).or_insert(0_usize) += 1;
        }
        if let Some(applicability) = item.applicability() {
            *applicability_counts
                .entry(applicability.as_str())
                .or_insert(0_usize) += 1;
        }
    }
    for (kind, count) in kind_counts {
        append(output, format_args!("| {kind} | {count} |\n"));
    }
    render_count_table(output, "Applicability totals", applicability_counts);
    render_count_table(output, "Disposition totals", disposition_counts);
    render_count_table(output, "Compatibility-impact totals", impact_counts);
}

fn render_count_table(output: &mut String, title: &str, counts: BTreeMap<&'static str, usize>) {
    append(output, format_args!("\n## {title}\n\n"));
    output.push_str("| Outcome | Items |\n| --- | ---: |\n");
    for (outcome, count) in counts {
        append(output, format_args!("| {outcome} | {count} |\n"));
    }
}

fn render_outcomes(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("\n## Item-level outcomes\n\n");
    output.push_str("| ID | Kind | Source identity | Applicability | Disposition | Impact | Evidence | Review |\n");
    output.push_str("| --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for item in manifest.items() {
        let applicability = item
            .applicability()
            .map_or("unresolved", Applicability::as_str);
        let disposition = item
            .disposition()
            .map_or("unresolved", TerminalDisposition::as_str);
        let impact = item
            .compatibility_impact()
            .map_or("unresolved", CompatibilityImpact::as_str);
        let evidence = item.evidence().map_or_else(
            || "unresolved".to_owned(),
            |mappings| {
                mappings
                    .iter()
                    .map(|mapping| {
                        format!(
                            "{}: [{}]({})",
                            mapping.kind().as_str(),
                            markdown(mapping.reference()),
                            mapping.reference()
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("<br>")
            },
        );
        let review = item.review().map_or_else(
            || "unresolved".to_owned(),
            |review| {
                format!(
                    "{} ({}) — {}",
                    markdown(review.reviewer()),
                    review.reviewed_on(),
                    prose(review.rationale())
                )
            },
        );
        append(
            output,
            format_args!(
                "| `{}` | {} | `{}` / `{}` | {} | {} | {} | {} | {} |\n",
                markdown(item.id()),
                item.kind().as_str(),
                markdown(item.source_path()),
                markdown(item.source_symbol()),
                applicability,
                disposition,
                impact,
                evidence,
                review
            ),
        );
    }
}

fn unresolved_count(manifest: &CorpusManifest) -> usize {
    manifest
        .items()
        .iter()
        .filter(|item| {
            item.applicability().is_none()
                || item.disposition().is_none()
                || item.compatibility_impact().is_none()
                || item.evidence().is_none()
                || item.review().is_none()
        })
        .count()
}

fn append(output: &mut String, arguments: Arguments<'_>) {
    output
        .write_fmt(arguments)
        .expect("writing semantic corpus report to a String cannot fail");
}

fn prose(value: &str) -> String {
    value.replace('\n', " ")
}

fn markdown(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
