//! Deterministic human projection of the validated semantic corpus authority.

use std::collections::BTreeMap;
use std::fmt::{Arguments, Write as _};

use super::corpus::model::{
    Applicability, CompatibilityImpact, CorpusManifest, TerminalDisposition,
};

#[derive(Clone, Copy)]
enum Alignment {
    Left,
    Right,
}

pub(super) fn render(manifest: &CorpusManifest) -> String {
    let mut output = String::new();
    output.push_str(
        "<!-- @generated by `cargo xtask inventory corpus generate-report`; DO NOT EDIT. -->\n\n",
    );
    output.push_str("# Upstream Semantic Corpus\n\n");
    output.push_str(
        "The machine-readable authority is `reference/upstream-corpus.json`. This projection records reviewed accounting and does not widen compatibility claims.\n\n",
    );
    render_identity(&mut output, manifest);
    render_counts(&mut output, manifest);
    render_outcomes(&mut output, manifest);
    output
}

fn render_identity(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("## Authority identity\n\n");
    append(
        output,
        format_args!("- Oracle revision: `{}`\n", manifest.oracle_revision()),
    );
    append(
        output,
        format_args!("- Semantic items: {}\n", manifest.items().len()),
    );
    append(
        output,
        format_args!("- Unresolved items: {}\n", unresolved_count(manifest)),
    );
}

fn render_counts(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("\n## Kind totals\n\n");
    let mut kind_counts = BTreeMap::new();
    let mut disposition_counts = BTreeMap::new();
    let mut impact_counts = BTreeMap::new();
    let mut applicability_counts = BTreeMap::new();
    for item in manifest.items() {
        *kind_counts.entry(item.kind().as_str()).or_insert(0_usize) += 1;
        if let Some(disposition) = item.disposition() {
            *disposition_counts
                .entry(disposition.as_str())
                .or_insert(0_usize) += 1;
        }
        if let Some(impact) = item.compatibility_impact() {
            *impact_counts.entry(impact.as_str()).or_insert(0_usize) += 1;
        }
        if let Some(applicability) = item.applicability() {
            *applicability_counts
                .entry(applicability.as_str())
                .or_insert(0_usize) += 1;
        }
    }
    render_count_rows(output, "Kind", kind_counts);
    render_count_table(output, "Applicability totals", applicability_counts);
    render_count_table(output, "Disposition totals", disposition_counts);
    render_count_table(output, "Compatibility-impact totals", impact_counts);
}

fn render_count_table(output: &mut String, title: &str, counts: BTreeMap<&'static str, usize>) {
    append(output, format_args!("\n## {title}\n\n"));
    render_count_rows(output, "Outcome", counts);
}

fn render_count_rows(
    output: &mut String,
    first_header: &str,
    counts: BTreeMap<&'static str, usize>,
) {
    let rows = counts
        .into_iter()
        .map(|(outcome, count)| [outcome.to_owned(), count.to_string()]);
    render_table(
        output,
        [first_header, "Items"],
        [Alignment::Left, Alignment::Right],
        rows,
    );
}

fn render_outcomes(output: &mut String, manifest: &CorpusManifest) {
    output.push_str("\n## Item-level outcomes\n\n");
    let rows = manifest.items().iter().map(|item| {
        let applicability = item
            .applicability()
            .map_or("unresolved", Applicability::as_str);
        let disposition = item
            .disposition()
            .map_or("unresolved", TerminalDisposition::as_str);
        let impact = item
            .compatibility_impact()
            .map_or("unresolved", CompatibilityImpact::as_str);
        let evidence = item.evidence().map_or_else(
            || "unresolved".to_owned(),
            |mappings| {
                mappings
                    .iter()
                    .map(|mapping| {
                        format!(
                            "{}: [{}]({})",
                            mapping.kind().as_str(),
                            markdown(mapping.reference()),
                            mapping.reference()
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("<br>")
            },
        );
        let review = item.review().map_or_else(
            || "unresolved".to_owned(),
            |review| {
                format!(
                    "{} ({}) — {}",
                    markdown(review.reviewer()),
                    review.reviewed_on(),
                    prose(review.rationale())
                )
            },
        );
        [
            format!("`{}`", markdown(item.id())),
            item.kind().as_str().to_owned(),
            format!(
                "`{}` / `{}`",
                markdown(item.source_path()),
                markdown(item.source_symbol())
            ),
            applicability.to_owned(),
            disposition.to_owned(),
            impact.to_owned(),
            evidence,
            review,
        ]
    });
    render_table(
        output,
        [
            "ID",
            "Kind",
            "Source identity",
            "Applicability",
            "Disposition",
            "Impact",
            "Evidence",
            "Review",
        ],
        [Alignment::Left; 8],
        rows,
    );
}

fn render_table<const COLUMN_COUNT: usize>(
    output: &mut String,
    headers: [&str; COLUMN_COUNT],
    alignments: [Alignment; COLUMN_COUNT],
    rows: impl IntoIterator<Item = [String; COLUMN_COUNT]>,
) {
    let rows = rows.into_iter().collect::<Vec<_>>();
    let mut widths = std::array::from_fn(|index| display_width(headers[index]));
    for row in &rows {
        for (index, cell) in row.iter().enumerate() {
            widths[index] = widths[index].max(display_width(cell));
        }
    }
    for (index, alignment) in alignments.iter().enumerate() {
        let minimum = match alignment {
            Alignment::Left => 3,
            Alignment::Right => 4,
        };
        widths[index] = widths[index].max(minimum);
    }

    let header_cells = headers.map(str::to_owned);
    render_table_row(output, &header_cells, &widths, &alignments);
    render_table_separator(output, &widths, &alignments);
    for row in &rows {
        render_table_row(output, row, &widths, &alignments);
    }
}

fn render_table_row<const COLUMN_COUNT: usize>(
    output: &mut String,
    cells: &[String; COLUMN_COUNT],
    widths: &[usize; COLUMN_COUNT],
    alignments: &[Alignment; COLUMN_COUNT],
) {
    output.push('|');
    for (index, cell) in cells.iter().enumerate() {
        output.push(' ');
        let padding = widths[index] - display_width(cell);
        if matches!(alignments[index], Alignment::Right) {
            append_spaces(output, padding);
        }
        output.push_str(cell);
        if matches!(alignments[index], Alignment::Left) {
            append_spaces(output, padding);
        }
        output.push_str(" |");
    }
    output.push('\n');
}

fn render_table_separator<const COLUMN_COUNT: usize>(
    output: &mut String,
    widths: &[usize; COLUMN_COUNT],
    alignments: &[Alignment; COLUMN_COUNT],
) {
    output.push('|');
    for (width, alignment) in widths.iter().zip(alignments) {
        output.push(' ');
        match alignment {
            Alignment::Left => output.extend(std::iter::repeat_n('-', *width)),
            Alignment::Right => {
                output.extend(std::iter::repeat_n('-', *width - 1));
                output.push(':');
            }
        }
        output.push_str(" |");
    }
    output.push('\n');
}

fn append_spaces(output: &mut String, count: usize) {
    output.extend(std::iter::repeat_n(' ', count));
}

fn display_width(value: &str) -> usize {
    value.chars().count()
}

fn unresolved_count(manifest: &CorpusManifest) -> usize {
    manifest
        .items()
        .iter()
        .filter(|item| {
            item.applicability().is_none()
                || item.disposition().is_none()
                || item.compatibility_impact().is_none()
                || item.evidence().is_none()
                || item.review().is_none()
        })
        .count()
}

fn append(output: &mut String, arguments: Arguments<'_>) {
    output
        .write_fmt(arguments)
        .expect("writing semantic corpus report to a String cannot fail");
}

fn prose(value: &str) -> String {
    markdown(value)
}

fn markdown(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}
